// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icmagqpmtdftxngitmcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljbWFncXBtdGRmdHhuZ2l0bWNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4ODI3MzQsImV4cCI6MjA1OTQ1ODczNH0.WfnOztWWhcVqB04C6PfSeXPs2nvOBqSupE3ktreLgj0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);